elementary/os-patches

debian/patches/fix-solarized-dark-draw-spaces.patch
debian/patches/series

A very subtle change, but hopefully makes the contrast _just about_ good enough to actually be able to see the dots when the text is selected. The selected background and unselected background are unfortunately too contrasting to find a really good color for this, and we can't have a different color for each.
We also don't want to end up making the dots stand out too much by making them really white or else it starts to look like part of the code.
Before:
After:

Improved solarized-dark spaces contrast

---

data/geoclue.conf.in

The `geoclue` key was getting rate limited, use our own.
Fixes https://github.com/elementary/os/issues/197

Use our MLS key

---

.github/workflows/juno.yml
README.md
get-latest-version.py

When we backport newer versions of packages, we usually take them from newer ubuntu releases.
In this case, our version will always be newer than the version in the current ubuntu series, so we won't get issue notifications when a new version gets published upstream.
This PR adds an extra argument to the python script to allow specifying the upstream series and in the package list, we can do something like:
`packagekit:disco`
Any lines without a colon are just assumed to be in the current series.

Allow specifying a different upstream series for backports

---

get-latest-version.py

I had tested this locally, but hadn't noticed that the bash while loop can pass empty rather than missing args to the python script.

Handle empty args to python script

---

bionic/packages_to_import

This syntax requires #70
I've created the necessary branches and tested the build locally in a pbuilder environment. I assume someone needs to set something up in launchpad to build this first though?

Add backported PackageKit 1.1.12

---

get-latest-version.py

This builds on #75, so that should be merged first.
Currently we throw an error if a package is missing from the PPA, which means execution of the workflow stops before checking any of the other packages further down the list.
Don't do this and open a GitHub issue instead.

Don't error out on missing package

---

data/50unattended-upgrades.Ubuntu

This should resolve the following error when running `dist-upgrade`:
```bash
E: Syntax error /etc/apt/apt.conf.d/50unattended-upgrades:14: Malformed tag
```
Related issues/pipelines:
https://elementaryos.stackexchange.com/questions/22584/update-for-unattended-updates-causes-problems
https://github.com/elementary/docker/pull/14/checks?check_run_id=500895498

fix an extra quote in apps security updates

---

data/geoclue.conf.in

Our key is expired and Mozilla hasn't given us a new one

Conf: Revert to upstream geoclue API key

---

focal/packages_to_import

Fixes #115 
I've created the necessary branches, we just need the launchpad recipe setting up.
The only patch I've added for the time being is to fix the draw-spaces contrast in the solarized themes. In `bionic` we had a bunch of other patches to add more language specs. We can add those later if necessary/still desired.

focal: Add gtksourceview4

---

debian/local/plymouth.hook

Closes https://github.com/elementary/os-patches/issues/163
@cassidyjames and @hanaral could you please test this:
You have to open `/usr/share/initramfs-tools/hooks/plymouth`
```
sudo nano /usr/share/initramfs-tools/hooks/plymouth
```
go to line 134 and replace this
```
if [ -e /usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf ]
then
sed 's|\(<family>DejaVu Sans</family>\)|<family>Ubuntu</family>\1|;s|\(<family>DejaVu Sans Mono<>
/etc/fonts/conf.d/60-latin.conf > "${DESTDIR}/etc/fonts/conf.d/60-latin.conf"
mkdir -p "${DESTDIR}/usr/share/fonts/truetype/ubuntu"
cp -a /usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf "${DESTDIR}/usr/share/fonts/truetype/ubuntu"
cp -a /usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf "${DESTDIR}/usr/share/fonts/truetype/ubu>
fi
```
with this
```
cp …
```

plymouth: Change default fonts

---

debian/update-grub

Fixes #178
Fixes #192 
Fixes #193 
This seems to be the cause of a common complaint about Odin where bootloader config doesn't get updated when installing new kernels etc.
Distinst installs GRUB so that its config is also contained on the `/boot/efi` partition, which differs from the Ubuntu default, so we can essentially re-alias the `update-grub` command to update to this location too. There's no harm in updating both locations, as only one config file gets loaded anyway. So if someone has re-installed their GRUB to load config from the default Ubuntu location instead of the distinst location, this will continue to work. This also works for legacy BIOS systems as that will load from /boot/grub/grub.cfg.

Re-alias update-grub command to elementary path

---

debian/grub-common.init
debian/grub-common.pm-sleep

Fixes #178 
Similar to #196 
The `recordfail` function of GRUB stores a flag in an environment file on every boot, which is then cleared by an init script or a wake script. If it's not cleared, the previous boot can be assumed to be a failure which then shows the GRUB menu on the next boot.
Since distinst is installing GRUB to a different location, we need to have the clearing scripts clear that location too.

Ensure recordfail state is cleared in our grubenv

---

jammy/packages_to_import

Looks like we got a successful build: https://code.launchpad.net/~elementary-os/+recipe/python-apt-jammy

packages_to_import: add python-apt

---

jammy/packages_to_import

I've tested and validated this patch to fix the issue of the installer not launching on the live image by creating the live session user as UID 1000 instead of 999. If we want to take this approach to fix this issue, we'll need to monitor the casper package for changes, so we can keep it up to date.
`casper` is only installed in the live session, so this will have no impact on installed systems.
https://github.com/elementary/os-patches/compare/casper-jammy...casper-jammy-patched
Related: https://github.com/elementary/greeter/issues/600

packages_to_import: add casper

---

dkms_common.postinst

I believe the DKMS patch for Jammy should be dropped as the flag it adds is [no longer in use for Jammy](https://github.com/elementary/os-patches/commit/f37a8064ab7849356e340a7c6dbdb9b8cb8f47bc).
For most users I imagine DKMS will be run as part of installing drivers via apt, thus the existing patches in apt adding the  `LSB_OS_RELEASE` environment variable should be sufficient at passing the check.
It might be possible to drop this package entirely from the os-patches repository as this was the only patch on it, but that might not play well with existing installations. Reverting and building an update seems safer. 
Was going to make an issue, but as it is a small change just made this pr.

Revert "Use upstream flag for lsb_release" on dkms

---

debian/etc.bash_preexec

Fixes #85
Rebased bash_preexec on https://github.com/rcaloras/bash-preexec/commit/da64ad4b7bb965d19dbeb5bb7447f1a63e3de2e3, while preserving the copyright header.
```
ryo@b760m:~/work/tmp/os-patches$ git rev-parse HEAD
ebf9032f2713876248c784e124329562c96a23ad
ryo@b760m:~/work/tmp/os-patches$ sudo cp ~/work/tmp/os-patches/debian/etc.bash_preexec /etc/bash_preexec
ryo@b760m:~/work/tmp/os-patches$ exec bash
ryo@b760m:~/work/tmp/os-patches$ cd ~/Downloads/
ryo@b760m:~/Downloads$ cd $_
ryo@b760m:~/Downloads$ 
exit
```

Rebase bash_preexec to upstream 0.5.0 release

---

grub-core/term/ns8250-spcr.c
include/grub/ieee1275/alloc.h

This fixes the debuild of grub2 fails (and hopefully fixes [the LP build failing](https://code.launchpad.net/~elementary-os/+archive/ubuntu/os-patches/+recipebuild/3771554); rebase `grub2-noble-patched` on `grub2-noble` after merging this branch)
```
user@VirtualBox-4c0cd87a:~/work/os-patches$ debuild -us -uc
:
dpkg-source: warning: diff os-patches/debian/patches/revert-term-ns8250-spcr.patch removes a non-existing file os-patches/grub-core/term/ns8250-spcr.c (line 59)
dpkg-source: info: applying revert-term-ns8250-spcr.patch
patching file docs/grub.texi
patching file grub-core/Makefile.core.def
The next patch would delete the file grub-core/term/ns8250-spcr.c,
which does not exist!  Skipping patch.
1 out of 1 hunk ignored
patching file grub-core/term/serial.c
patching file …
```

Reimport grub2_2.12-1ubuntu7 from packages.ubuntu.com

---

.github/workflows/horus.yml
.github/workflows/juno.yml
.github/workflows/noble.yml
.github/workflows/odin.yml
get-latest-version.py

This rewrites the Python script that compares packages.
Should work. Proof: https://github.com/stsdc/os-patches/actions/runs/13398951005/job/37424819616
Also PRs created successfully: https://github.com/stsdc/os-patches/pulls
Notable changes:
* Using python script to get list of patched packages from `/tmp/patched-packages`. Previously it was done in shell in the workflow. When we're doing this in python script, we do not have to execute login and connect to the PPA
* Using GitPython library to perform actions on git repository. Previously it was done by executing shell commands in Python script. It wasn't reliable, looks like there were some race conditions and it failed sometimes on first package and sometimes later (but I'm not 100% sure)
* The script is now parsing `apt source …

Fix getting latest version

---

README.md
get-latest-version.py

`*` does not include hidden files like `.gitignore`, which results our import being incomplete.

Import hidden files too

---

etc/upstream-os-release

This fixes the System plug says that latest elementary OS 8.0.1 is built on Ubuntu 24.04.1 LTS.
Please [sync Launchpad source with GitHub](https://code.launchpad.net/~elementary-os/elementaryos/+git/os-patches) and then request build of [base-files-noble](https://code.launchpad.net/~elementary-os/+recipe/base-files-noble) on Launchpad once this PR get merged. I don't have privilege to do this.
```
git clone https://github.com/elementary/os-patches.git
cd os-patches/
git switch ryonakano/base-files-noble-patched-update-version 
sudo apt install devscripts build-essential 
sudo apt build-dep base-files
debuild -us -uc
sudo apt install -y --allow-downgrades ../base-files_13ubuntu10.2_amd64.deb 
```

upstream-os-release: Update Ubuntu version

---

get-latest-version.py

Currently the `grub2-noble` branch (not the `-patched` one) fails to build with `debuild -us -uc` because the leftovers that no longer exists in the original source are detected as local changes:
```
dpkg-source: info: local changes detected, the modified files are:
os-patches/grub-core/term/ns8250-spcr.c
os-patches/include/grub/ieee1275/alloc.h
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/grub2_2.12-1ubuntu7.1.diff.6Yf8OW
```
This PR removes all files/directories excluding `.`, `..`, and `.git` before copying upstream source to prevent files/directories removed in upstream from being leftover.

Make sure not to leave files/directories that removed in upstream

---

get-latest-version.py

Regression of #314
This fixes the Actions is failing these days with the following error:
```
Traceback (most recent call last):
base-files noble
dpkg-source: info: extracting base-files in base-files-13ubuntu10.3
File "/__w/os-patches/os-patches/get-latest-version.py", line 179, in <module>
File "/__w/os-patches/os-patches/get-latest-version.py", line 150, in main
File "/usr/lib/python3.12/subprocess.py", line 571, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cp -r base-files-13ubuntu10.3/. .' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```
This is because we clean up the working directory **after** retrieving the source code with `apt source`, which means the retrieved source is wiped out and thus `cp -r` …

get-latest-version: Fix the apt-sourced directory is cleaned up
